# Generated by Django 4.1.2 on 2022-10-28 20:31

import audioapi.models.session
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticks', models.CharField(max_length=200, validators=[audioapi.models.session.validate_ticks])),
                ('selected_tick', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(0)])),
                ('step_count', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='AudioUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiouser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_audio', to='audioapi.audiouser')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_session', to='audioapi.session')),
            ],
        ),
    ]
