# Generated by Django 4.1.2 on 2022-10-31 19:13

import audioapi.models.session
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='ticks',
            field=models.JSONField(max_length=200, validators=[audioapi.models.session.validate_ticks]),
        ),
    ]
