# Generated by Django 4.1.2 on 2022-11-01 21:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audioapi', '0002_alter_session_ticks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_count', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='step_count',
        ),
        migrations.AddField(
            model_name='session',
            name='audiouser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_audio', to='audioapi.audiouser'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
        migrations.AddField(
            model_name='step',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_steps', to='audioapi.session'),
        ),
    ]
