# Generated by Django 4.1.2 on 2022-11-02 17:14

import audioapi.models.step
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapi', '0003_step_remove_session_step_count_session_audiouser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='selected_tick',
        ),
        migrations.RemoveField(
            model_name='session',
            name='ticks',
        ),
        migrations.AddField(
            model_name='step',
            name='selected_tick',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='step',
            name='ticks',
            field=models.JSONField(default=[-96.33, -96.33, -93.47, -89.03999999999999, -84.61, -80.18, -75.75, -71.32, -66.89, -62.46, -58.03, -53.6, -49.17, -44.74, -40.31], max_length=200, validators=[audioapi.models.step.validate_ticks]),
            preserve_default=False,
        ),
    ]
